version: '3.3'
services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3306:3306'